remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: NICOLAI
subtitle: Artist - Musician - Researcher - Explorer - Human
mainquote: The privilege of a lifetime is being who you are.
mainquoteperson: Joseph Campbell

theme: jekyll-theme-midnight
