remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Hello!
description: My name is Nick Lai. Below is a sample of the many things I've been involved with over the years. Enjoy!

theme: jekyll-theme-midnight
